final_project/aphorism/accounts/urls.py
from django.urls import path, include, reverse_lazy
from .views import RegisterUser, LoginUser, user_logout, settings
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [path('register', RegisterUser.as_view(), name='register'),
               path('login', LoginUser.as_view(), name='login'),
               path('logout', user_logout, name='logout'),
               path('settings', settings, name='settings'),
               path('password_change', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),
               path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
               path('password_reset', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),#email_template_name='registration/password_reset_email.html'
               path('password_reset_sent', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
               path('password/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
                    name='password_reset_confirm'),
               path('password/reset/done', auth_views.PasswordResetCompleteView.as_view(),
                    name='password_reset_complete')]

final_project/aphorism/aphorism/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('scrap.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include('fin_api.urls')),
    path('api/auth/', include('djoser.urls')),
    re_path('api/auth/', include('djoser.urls.authtoken'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

final_project/aphorism/scrap/urls.py
from django.urls import path
from .views import AphListView, AphView, AddAph, UpdateAph, DeleteAph, fav_add, SendMes, Sentes, Sms, DeleteMes, \
    UsersList, UserDelete, UserView, UserUpdate, AddPhoto, set_main, delete_photo, friend_send, friend_requests, \
    friend_response, friend_reject
from django.contrib.auth.decorators import login_required

app_name = 'scrap'
urlpatterns = [path('', AphListView.as_view(), name='get_aphs'),
               path('mess', login_required(SendMes.as_view()), name='mess'),
               path('sent', login_required(Sentes.as_view()), name='sent'),
               path('sms', Sms.as_view(), name='sms'),
               path('delete_mes/<pk>', DeleteMes.as_view(), name='delete_mes'),
               path('add', AddAph.as_view(), name='add'),
               path('update/<pk>', login_required(UpdateAph.as_view()), name='update'),
               path('delete/<pk>', login_required(DeleteAph.as_view()), name='delete'),
               path('/<pk>', AphView.as_view(), name='aph'),
               path('fav/<i>', login_required(fav_add), name='fav_add'),
               path('users_list', login_required(UsersList.as_view()), name='users_list'),
               path('user_update/<pk>', login_required(UserUpdate.as_view()), name='user_update'),
               path('user_delete/<pk>', login_required(UserDelete.as_view()), name='user_delete'),
               path('users_list/<pk>', login_required(UserView.as_view()), name='user_view'),
               path('add_photo', login_required(AddPhoto.as_view()), name='add_photo'),
               path('set_main/<j>', login_required(set_main), name='set_main'),
               path('delete_photo/<i>', login_required(delete_photo), name='delete_photo'),
               path('friend_send/<i>', login_required(friend_send), name='friend_send'),
               path('friend_requests', login_required(friend_requests), name='friend_requests'),
               path('friend_response/<i>', login_required(friend_response), name='friend_response'),
               path('friend_reject/<i>', login_required(friend_reject), name='friend_reject')
               ]

final_project/aphorism/scrap/models.py
from django.db import models
from django.contrib.auth.models import User



class Authors(models.Model):
    author = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.author}'


class Tags(models.Model):
    tag = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return f'{self.tag}'


class Quotas(models.Model):
    quota = models.TextField(null=False)
    author = models.ForeignKey(Authors, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tags)
    fav = models.ManyToManyField(User, related_name='favor', blank=True)
    picture = models.ImageField(upload_to='media', blank=True, null=True)
    download = models.FileField(upload_to='media', blank=True, null=True)
    date = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return f'{self.quota}'


class Messege(models.Model):
    messege = models.TextField(null=True,  blank=True)
    nkar = models.ImageField(upload_to='media', blank=True, null=True)
    sender = models.ForeignKey(User, related_name='send', on_delete=models.SET_NULL, null=True)
    reciever = models.ForeignKey(User, related_name='reciev', on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return f'{self.messege}'

class UsersPhotos(models.Model):
    comment = models.CharField(max_length=50)
    is_main = models.BooleanField(default=False)
    image = models.ImageField(upload_to='media', blank=False)
    date = models.DateTimeField(auto_now=True, blank=True)
    user_photo=models.ForeignKey(User, blank=False, on_delete=models.CASCADE)

class Friends(models.Model):

    friend_sender = models.ForeignKey(User, related_name='f_s', on_delete=models.CASCADE, null=True)
    friend_reciever = models.ForeignKey(User, related_name='f_r', on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now=True, blank=True)
    subscribe = models.BooleanField(default=False)

final_project/aphorism/scrap/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Quotas, Tags, Authors, Messege
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    quota = forms.CharField(label='Quote', required=False, widget=forms.TextInput(attrs={'class': 'formclass'}))
    author = forms.ModelChoiceField(queryset=Authors.objects.all(),  label='Author', required=False)
    tag = forms.ModelChoiceField(queryset=Tags.objects.all(),  label='Tags', required=False)

    class Meta:
        model = Quotas
        fields = ('quota', 'author', 'tag')

class UserSearchForm(forms.Form):
    username = forms.CharField(label='Find users', required=False, widget=forms.TextInput(attrs={'placeholder':'username, name, last_name'}))


    class Meta:
        model = User
        fields = ('username', )

class MessegeSearchForm(forms.Form):
    sender = forms.CharField(label='Search', required=False, widget=forms.TextInput(attrs={'class': 'formclass'}))

    class Meta:
        model = Messege
        fields = ('sender',)

final_project/aphorism/scrap/views.py
import os
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, HttpResponseRedirect
from .models import Authors, Quotas, Tags, Messege, UsersPhotos, Friends
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from .forms import SearchForm, MessegeSearchForm, UserSearchForm
from django.contrib.auth.models import User


class AphListView(ListView):
    model = Quotas
    paginate_by = 10
    template_name = 'list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = SearchForm()
        return context

    def get_queryset(self):
        object_list = Quotas.objects.all().order_by('-date')

        if 'quota' in self.request.GET and self.request.GET['quota']:
            quota = self.request.GET['quota']
            object_list = object_list.filter(quota__icontains=quota)

        if 'author' in self.request.GET and self.request.GET['author']:
            author = self.request.GET['author']
            object_list = object_list.filter(author=author)

        if 'tag' in self.request.GET and self.request.GET['tag']:
            tag = self.request.GET['tag']
            object_list = object_list.filter(tag=tag)

        if 'user' in self.request.GET:
            object_list = object_list.filter(user=self.request.user)

        if 'fav' in self.request.GET:
            # fav = self.request.GET['fav']
            object_list = object_list.filter(fav=self.request.user)

        return object_list


class AphView(DetailView):
    model = Quotas
    template_name = 'aph.html'


class AddAph(LoginRequiredMixin, CreateView):
    model = Quotas
    fields = ('quota', 'tag', 'picture')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add quote'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        if self.request.user.first_name:
            auth = f'{self.request.user.first_name} {self.request.user.last_name}'
            a, _ = Authors.objects.get_or_create(author=auth)
            form.instance.author = a
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('scrap:get_aphs')


class UpdateAph(LoginRequiredMixin, UpdateView):
    model = Quotas
    fields = ('quota', 'tag', 'picture')
    template_name_suffix = '_update_form'

    def get_queryset(self):
        object_list = Quotas.objects.filter(user=self.request.user)
        return object_list

    def get_success_url(self):
        return reverse('scrap:aph', args=[self.object.id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'update quote'
        return context


class DeleteAph(LoginRequiredMixin, DeleteView):
    model = Quotas
    success_url = reverse_lazy('scrap:get_aphs')

    def form_valid(self, form):
        success_url = self.get_success_url()
        q = Quotas.objects.filter(user=self.request.user).all()
        if len(q) < 2:
            Authors.objects.filter(author=q[0].author).delete()
        if self.object.picture:
            file_path = os.getcwd() + f'/media/{self.object.picture}'
            os.remove(file_path)
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_queryset(self):
        object_list = Quotas.objects.filter(user=self.request.user)

        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'delete quote'
        return context


def fav_add(request, i):
    quote = get_object_or_404(Quotas, id=i)

    if quote.fav.filter(id=request.user.id).exists():
        quote.fav.remove(request.user)
    else:
        quote.fav.add(request.user)
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


'''messege send implementation 128-'''


class SendMes(LoginRequiredMixin, CreateView):
    model = Messege
    fields = ('messege', 'nkar')
    success_url = reverse_lazy('scrap:mess')


    @staticmethod
    def f(req):
        q = req.GET['rec']
        if q.replace(req.user.username, ''):
            f = q.replace(req.user.username, '')
        else:
            f = req.user.username
        return f

    def form_valid(self, form):
        if form.instance.messege or form.instance.nkar:
            f = self.f(self.request)
            rec = get_object_or_404(User, username=f)
            form.instance.sender = self.request.user
            form.instance.reciever = rec
            return super().form_valid(form)
        else:
            return HttpResponseRedirect(self.request.META["HTTP_REFERER"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        f = self.f(self.request)
        context['rec'] = self.f(self.request)
        obj = Messege.objects.filter(Q(reciever=self.request.user, sender__username=f) |
                                     Q(sender=self.request.user, reciever__username=f)).order_by('date')
        context['object_list'] = obj
        return context

    def get_success_url(self):
        return self.success_url + '?rec=' + self.object.sender.username + self.object.reciever.username


class Sentes(LoginRequiredMixin, ListView):
    model = Messege
    paginate_by = 10
    template_name = 'user_messeges.html'

    def get_queryset(self):
        object_list = Messege.objects.filter(
            Q(reciever=self.request.user) | Q(sender=self.request.user)).order_by('-date')
        if 'sender' in self.request.GET and self.request.GET['sender']:
            sender = self.request.GET['sender']
            object_list = object_list.filter(
                ((Q(reciever__username__contains=sender) | Q(reciever__first_name__contains=sender))
                 & ~Q(reciever=self.request.user)) | (
                        (Q(sender__username__contains=sender) | Q(reciever__first_name__contains=sender))
                        & ~Q(sender=self.request.user)))

        l = []
        m = []
        for i in object_list:
            if i.sender == self.request.user and i.reciever not in l:
                l.append(i.reciever)
                m.append(i)
            elif i.sender != self.request.user and i.sender not in l:
                l.append(i.sender)
                m.append(i)

        object_list = m

        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = MessegeSearchForm()
        return context


class Sms(LoginRequiredMixin, ListView):
    model = Messege
    paginate_by = 10
    template_name = 'sms_messeges.html'

    def get_queryset(self):
        q = self.request.GET['param']
        if q.replace(self.request.user.username, ''):
            f = q.replace(self.request.user.username, '')
        else:
            f = self.request.user.username
        object_list = Messege.objects.filter(Q(reciever=self.request.user, sender__username=f) |
                                             Q(sender=self.request.user, reciever__username=f)).order_by('-date')

        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['other'] = self.request.GET['param']
        return context


class DeleteMes(LoginRequiredMixin, DeleteView):
    model = Messege
    success_url = reverse_lazy('scrap:mess')

    def get_queryset(self):
        object_list = Messege.objects.filter(
            Q(reciever=self.request.user) | Q(sender=self.request.user))
        return object_list

    def form_valid(self, form):
        success_url = self.get_success_url()
        if self.object.nkar:
            file_path = os.getcwd() + f'/media/{self.object.nkar}'
            os.remove(file_path)
        self.object.delete()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return self.success_url + '?rec=' + self.object.sender.username + self.object.reciever.username


# object_list=User.objects.filter(Q(send__reciever=self.request.user) |
# Q(reciev__sender=self.request.user)).order_by('-send__date')#.distinct()

#data['requests'] = User.objects.filter(f_s__friend_reciever=request.user).all(),
#sa /f_s related_name na Friends um u User objecta/ nshanakuma request uxarkac user/ nshanakuma ayn usernery /User/-ic, voronc hamapatasxan friend_reciever /Friends/-um havasara request.user in

'''users search form, users photos, accounts'''


class UsersList(LoginRequiredMixin, ListView):
    model = User
    paginate_by = 10
    template_name = 'users_list.html'


    def get_queryset(self):
        object_list = User.objects.all()

        if 'username' in self.request.GET:
            search_query = self.request.GET['username']
            object_list = object_list.filter(Q(username__icontains=search_query) |
                                             Q(first_name__icontains=search_query) |
                                             Q(last_name__icontains=search_query))

        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_photos'] = UsersPhotos.objects.filter(is_main=True).all()
        context['search_form'] = UserSearchForm
        context['friend'] = Friends.objects.filter(
            Q(friend_reciever=self.request.user) | Q(friend_sender=self.request.user)).all()



        return context


class UserView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'one_user.html'

    def get_context_data(self, **kwargs):

final_project/aphorism/scrap/templates/friend_request_list.html
{% extends "base.html" %}


{% block content %}


<br><br>

    {%if request.user.is_authenticated%}





{% for req in requests %}

        <div class="container d-flex mt-5" style="border:6px inset grey;border-radius: 7px;padding:5px;width: 500px;height:100px">
<h5 class="text-center"><a style="text-decoration:none;color:black;margin:10px" href="{%url 'scrap:user_view' req.id%}"><i> {{ req.username }}</i></a></h5>

            <br><br>

           <p style="margin:20px"> <b>{%if req.first_name%}{{req.first_name}} {{req.last_name}}{%endif%}</b></p>

{%for friend in friend_subscribe%}
            {% if friend.friend_sender == req %}
            {%if friend.subscribe == True %}
<h5 style="margin:30px;color:green" class="text-center"> Friend</h5>
 <a href="{% url 'scrap:friend_reject' req.id %}" ><button style="float:right;margin-left:3px;background:#c4341a" class="btn btn-primary btn-sm">remove friend </button></a>
            {%else%}
            <a href="{% url 'scrap:friend_response' req.id %}" ><button style="float:top;margin-left:80px;background:#749d52" class="btn btn-primary btn-sm">add friend </button></a>
 <a href="{% url 'scrap:friend_reject' req.id %}" ><button style="float:top;margin-left:10px;background:#c4341a" class="btn btn-primary btn-sm">reject friend </button></a>
{%endif%}
{%endif%}
            {%endfor%}




            <br>

           </div>



    {%endfor%}


{%endif%}
 {% endblock content %}

final_project/aphorism/scrap/templates/list.html
{% extends "base.html" %}


{% block content %}


<br><br>
<div style="float:right;margin-right:20px" ;>
    {%if request.user.is_authenticated%}

    <a href="{% url 'accounts:logout' %}">
        <button class="btn btn-primary btn-sm" >Logout</button>
    </a>
    {%else%}

    <a style="text-decoration:none" href="{% url 'accounts:register' %}">
        <button  class="btn btn-primary btn-sm">SignUp</button>
    </a>
    <a href="{% url 'accounts:login' %}" style="margin-left:5px;text-decoration:none">
        <button  class="btn btn-primary btn-sm">Login</button>
    </a>
    {%endif%}
</div>
<div class="container d-flex justify-content-center mt-12" style="width: 70%;">

    <div class="col mt-12">
        <form action="{% url 'scrap:get_aphs' %}" method="GET">

            {{ search_form }}
            <input type="submit" class="btn btn-primary btn-sm" value="Search" style="float:right">
        </form>
    </div>
</div>


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">



        {% for aph in object_list %}
        <div style="border:6px inset grey;border-radius: 7px;padding:10px">


            <h5 class="text-center"><a style="text-decoration:none;color:black;" href="{%url 'scrap:aph' aph.id%}"><i> {{ aph.quota }}</i></a></h5>
            <br>

            {%if aph.user%}

           <td class="text-center">by: <b>{%if aph.user.first_name%}{{aph.author}}{%else%}{{aph.user.username}}{%endif%}</b></td>
            {%else%}
            <td class="text-center">by <b><a style="color:grey" target="_blank" href="https://en.wikipedia.org/wiki/{{aph.author}}">{{ aph.author }}</a></b></td>
            {%endif%}
            {%if request.user.is_authenticated%}

            <a href="{% url 'scrap:mess'%}?rec={{aph.user.username}}">Messege</a>

            {%endif%}
            <p style="margin-bottom:-5%">{{ aph.date.date }}</p>
            {%if aph.picture%}
            <img src="{{ aph.picture.url }}" style="width:70px;margin-left:40%" alt="My image">
            {%endif%}
            <br><br>

            <td>Tags: {% for tag in aph.tag.all %}<a style="text-decoration:none;" href="{% url 'scrap:get_aphs' %}?tag={{tag.id}}"><button style="background:grey;border-radius:4px;">{{ tag }} </button> </a>{% endfor %}</td>

{%if request.user.is_authenticated %}

{%if request.user in aph.fav.all %}
          <a href="{% url 'scrap:fav_add' aph.id %}" ><button style="float:top;margin-left:3px;background:#c4341a" class="btn btn-primary btn-sm">rem from favs </button></a>
{%else%}
            <a href="{% url 'scrap:fav_add' aph.id %}" ><button style="float:top;margin-left:10px;background:#749d52" class="btn btn-primary btn-sm">Add to favs </button></a>


  {%endif%}

            {%endif%}


   {%if request.user.is_authenticated and request.user == aph.user %}

<a href="{% url 'scrap:delete' aph.id %}" ><button style="float:right;margin-left:5px;background:#dc143c" class="btn btn-primary btn-sm">Delete </button></a>
<a href="{% url 'scrap:update' aph.id %}" ><button style="float:right" class="btn btn-primary btn-sm">Update </button></a>

    {%endif%}
            </div>
 <br><br>


        {% endfor %}

        {%if request.user.is_authenticated%}
        <a class="btn btn-primary" href="{% url 'scrap:add' %}">Add new quote</a><br><br>
        {%endif%}
        {% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}

{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
        </div>
    </div>
    {% endblock content %}

final_project/aphorism/scrap/templates/one_user.html
{% extends 'base.html' %}
{%load static%}


{% block content %}

{%if request.user.is_authenticated%}


<div style="margin:30px;border-style: double;padding:10px">
    <h5>{{ object.username }}</h5><br>

    <h6 class="text-center"><b>{{ object.first_name }} {{ object.last_name }}</b></h6>
    {%for photo in one_user_photos%}

    <th><img src="{{ photo.image.url }}" style="width:100px;margin:1%" alt="My image"></th>

    {%endfor%}
    {%if request.user == object%}
<a   href="{%url 'accounts:settings'%}"><button style="margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">Settings </button></a>
{%endif%}
    {% if friend %}
    {% if friend.subscribe == True%}
<a href="{% url 'scrap:friend_reject' object.id %}">
        <button style="float:right;margin-left:3px;background:#c4341a" class="btn btn-primary btn-sm">remove friend
        </button>
    </a>
    <h5 style="margin-right:8px;color:green;float:right" class="text-center"> Friend</h5>

    {% elif friend.friend_reciever == request.user %}
    <a href="{% url 'scrap:friend_reject' object.id %}">
        <button style="float:right;margin-left:10px;background:#c4341a" class="btn btn-primary btn-sm">reject friend
        </button>
    </a>
    <a href="{% url 'scrap:friend_response' object.id %}">
        <button style="float:right;background:#749d52" class="btn btn-primary btn-sm">accept friend</button>
    </a>
  {%elif friend.friend_reciever == object %}
<a href="{% url 'scrap:friend_send' object.id %}" ><button style="float:right;margin-left:3px;background:white"
                                                               class="btn btn-primary btn-sm">cancel request </button></a>
    {%endif%}
     {%else%}
    <a href="{% url 'scrap:friend_send' object.id %}" ><button style="float:right;margin-left:3px;background:#749d52"
                                                               class="btn btn-primary btn-sm">add friend </button></a>
    {%endif%}

    <br>


</div>
{% for aph in quotas %}
<div style="width:60%;border:6px inset grey;border-radius: 7px;padding:10px">


    <h5 class="text-center"><i> {{ aph.quota }}</i></h5>
    <br>


    <td class="text-center">by: <b>{{aph.user.username}}</b></td>


    <p style="margin-bottom:-5%">{{ aph.date.date }}</p>
    {%if aph.picture%}
    <img src="{{ aph.picture.url }}" style="width:70px;margin-left:40%" alt="My image">
    {%endif%}
    <br><br>

    <td>Tags: {% for tag in aph.tag.all %}<a style="text-decoration:none;"
                                             href="{% url 'scrap:get_aphs' %}?tag={{tag.id}}">
        <button style="background:grey;border-radius:4px;">{{ tag }}</button>
    </a>{% endfor %}
    </td>


    {%if request.user in aph.fav.all %}
    <a href="{% url 'scrap:fav_add' aph.id %}">
        <button style="float:top;margin-left:3px;background:#c4341a" class="btn btn-primary btn-sm">rem from favs
        </button>
    </a>
    {%else%}
    <a href="{% url 'scrap:fav_add' aph.id %}">
        <button style="float:top;margin-left:10px;background:#749d52" class="btn btn-primary btn-sm">Add to favs
        </button>
    </a>


    {%endif%}


</div>
<br><br>

{% endfor %}
<a href="{% url 'scrap:get_aphs' %}">Go back</a>{%endif%}


{%endblock%}

final_project/aphorism/scrap/templates/users_list.html
{% extends "base.html" %}


{% block content %}


<br><br>
<div style="float:right;margin-right:20px" ;>
    {%if request.user.is_authenticated%}



</div>
<div class="container d-flex justify-content-center mt-12" style="width: 70%;">


        <form action="{% url 'scrap:users_list' %}" method="GET">

            {{ search_form }}
            <input type="submit" class="btn btn-primary btn-sm" value="Search" style="float:right">
        </form>
    </div>



<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">



        {% for us in object_list %}
        <div style="border:6px inset grey;border-radius: 7px;padding:10px">
                {%for photo in main_photos%}
                {%if photo.user_photo == us%}

            <img src="{{ photo.image.url }}" style="width:60px;margin:1%" alt="My image">
{%endif%}
            {%endfor%}
            <h5 class="text-center"><a style="text-decoration:none;color:black;" href="{%url 'scrap:user_view' us.id%}"><i> {{ us.username }}</i></a></h5>
            <br>


           <td class="text-center"> <b>{%if us.first_name%}{{us.first_name}} {{us.last_name}}{%endif%}</b></td>


            <a href="{% url 'scrap:mess'%}?rec={{us.username}}">Messege</a>

{%if request.user != us %}

    {%for i in friend%}

        {%if i.friend_sender == us or i.friend_reciever == us%}
            {%if i.subscribe == True%}
                  <h5 style="margin:30px;color:green" class="text-center"> Friend</h5>
            {%elif i.friend_reciever == us%}
      <a href="" ><button style="float:top;margin-left:3px;background:orange" class="btn btn-primary btn-sm">sent </button></a>
            {%endif%}
          {%endif%}
{%endfor%}





{%endif%}






            <br><br>


           </div>
 <br><br>

{%endfor%}

    </div>
    </div>


        {% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}

{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
        </div>
    </div>
{% endif %}
    {% endblock content %}