final_project/aphorism/accounts/urls.py
from django.urls import path, include, reverse_lazy
from .views import RegisterUser, LoginUser, user_logout, settings
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [path('register', RegisterUser.as_view(), name='register'),
               path('login', LoginUser.as_view(), name='login'),
               path('logout', user_logout, name='logout'),
               path('settings', settings, name='settings'),
               path('password_change', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),
               path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
               path('password_reset', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),#email_template_name='registration/password_reset_email.html'
               path('password_reset_sent', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
               path('password/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
                    name='password_reset_confirm'),
               path('password/reset/done', auth_views.PasswordResetCompleteView.as_view(),
                    name='password_reset_complete')]

final_project/aphorism/aphorism/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('scrap.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include('fin_api.urls')),
    path('api/auth/', include('djoser.urls')),
    re_path('api/auth/', include('djoser.urls.authtoken'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

final_project/aphorism/scrap/urls.py
from django.urls import path
from .views import AphListView, AphView, AddAph, UpdateAph, DeleteAph, fav_add, SendMes, Sentes, Sms, DeleteMes, \
    UsersList, UserDelete, UserView, UserUpdate, AddPhoto, set_main, delete_photo, friend_send, friend_requests, \
    friend_response, friend_reject
from django.contrib.auth.decorators import login_required

app_name = 'scrap'
urlpatterns = [path('', AphListView.as_view(), name='get_aphs'),
               path('mess', login_required(SendMes.as_view()), name='mess'),
               path('sent', login_required(Sentes.as_view()), name='sent'),
               path('sms', Sms.as_view(), name='sms'),
               path('delete_mes/<pk>', DeleteMes.as_view(), name='delete_mes'),
               path('add', AddAph.as_view(), name='add'),
               path('update/<pk>', login_required(UpdateAph.as_view()), name='update'),
               path('delete/<pk>', login_required(DeleteAph.as_view()), name='delete'),
               path('/<pk>', AphView.as_view(), name='aph'),
               path('fav/<i>', login_required(fav_add), name='fav_add'),
               path('users_list', login_required(UsersList.as_view()), name='users_list'),
               path('user_update/<pk>', login_required(UserUpdate.as_view()), name='user_update'),
               path('user_delete/<pk>', login_required(UserDelete.as_view()), name='user_delete'),
               path('users_list/<pk>', login_required(UserView.as_view()), name='user_view'),
               path('add_photo', login_required(AddPhoto.as_view()), name='add_photo'),
               path('set_main/<j>', login_required(set_main), name='set_main'),
               path('delete_photo/<i>', login_required(delete_photo), name='delete_photo'),
               path('friend_send/<i>', login_required(friend_send), name='friend_send'),
               path('friend_requests', login_required(friend_requests), name='friend_requests'),
               path('friend_response/<i>', login_required(friend_response), name='friend_response'),
               path('friend_reject/<i>', login_required(friend_reject), name='friend_reject')
               ]

final_project/aphorism/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{%load static%}
    <!-- Bootstrap CSS -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

    {%block title%}
        {%if title%}
            <title>{{ title }} | Aphorisms</title>
        {%else%}
            <title>Aphorisms</title>
        {% endif %}
    {%endblock title%}



{%block head%}

    {%endblock head%}

    </head>

<body>
{{ redirect_to_login_immediately }}
<div style="border:2px solid #2f4f4f;border-radius: 7px ;margin:10px; background-image: url('{% static 'cropped.png' %}');height:145px">

<a href="{% url 'scrap:get_aphs' %}"><img src="{% static 'navig.png' %}" style="width:245px;float:left" alt="My image"></a><br>
{%if request.user.is_authenticated%}
    <a   href="{%url 'accounts:settings'%}"><button style="float:right;margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">Account </button></a>
    <a   href="{%url 'scrap:sent'%}"><button style="float:right;margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">Messege </button></a>
    <a  href="{%url 'scrap:users_list'%}"><button style="float:right;margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">Users </button></a>
    <a  href="{%url 'scrap:friend_requests'%}"><button style="float:right;margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">Friends </button></a>
    {%endif%}

{%if request.user.is_authenticated%}

    <a  href="{%url 'scrap:get_aphs'%}?fav=fav"><button style="float:right;margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">Favorites </button></a>
   <a  href="{%url 'scrap:get_aphs'%}?user=self"><button style="float:right;margin-left:5px;background:#3B9C9C" class="btn btn-primary btn-sm">{{request.user.username}}</button></a>
    {%endif%}
</div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div class="container-fluid">

    <!-- NAVIGATION BAR -->




    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>-->

</body>

</html>